Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

  config.vm.define "router" do |router|
    router.vm.hostname = "router"
    router.vm.network "private_network", ip: '192.168.11.152', name: "vboxnet0"
    router.vm.network "private_network", ip: "192.168.0.5", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "elk-lab"
    router.vm.provider :virtualbox do |vb|
      vb.name = "router"
      vb.memory = 512
      vb.cpus = 1
    end
#    router.vm.provision "shell", run: "always", inline: <<-SHELL
#    echo 1 > /proc/sys/net/ipv4/ip_forward
#    iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.168.0.2:80
#    iptables -t nat -I POSTROUTING -p tcp --dst 192.168.0.2 --dport 80 -j SNAT --to 192.168.0.5
#    iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 192.168.0.4:80
#    iptables -t nat -I POSTROUTING -p tcp --dst 192.168.0.4 --dport 80 -j SNAT --to 192.168.0.5
#    SHELL
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.hostname = "mysql"
    mysql.vm.network "private_network", ip: "192.168.0.3", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "elk-lab"
    mysql.vm.provider :virtualbox do |vb|
      vb.name = "mysql"
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.0.2", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "elk-lab"
    web.vm.network "private_network", ip: '192.168.11.150', adapter: 3, netmask: "255.255.255.0", name: "vboxnet0"
    web.vm.provider :virtualbox do |vb|
      vb.name = "web"
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "backup" do |backup|
    backup.vm.hostname = "backup"
    backup.vm.network "private_network", ip: "192.168.0.4", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "elk-lab"
    backup.vm.network "private_network", ip: '192.168.11.151', adapter: 3, netmask: "255.255.255.0", name: "vboxnet0"
    backup.vm.provider :virtualbox do |vb|
      vb.name = "backup"
      vb.memory = 512
      vb.cpus = 1
      needsController = false
      unless File.exist?('./sata1.vdi')
        vb.customize ['createhd', '--filename', './sata1.vdi', '--variant', 'Fixed', '--size', 2048]
        needsController =  true
      end
      vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './sata1.vdi']
    end
  end

end
